spring:
  application:
    name: Farmacia-db
  datasource:
    url: jdbc:mysql://localhost:3307/farm
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.format_sql: true

